# Generated by Django 4.2.3 on 2023-07-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiDNA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dna_body', models.FileField(upload_to='')),
                ('dna_parents', models.FileField(upload_to='')),
                ('encoded', models.FileField(upload_to='')),
            ],
        ),
    ]
